# Generated by Django 6.0.1 on 2026-01-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
